#!/bin/sh
bash -c 'cd zstd/lib;make PREFIX=/usr CFLAGS=-fPIC install-includes install-static; make clean'
bash -c 'cd zstd/lib;make PREFIX=/usr LIBDIR=/usr/lib32 CFLAGS="-fPIC -m32" install-static; make clean'
