#!/bin/sh
bash -c "cd zstd/lib;make PREFIX=/usr LIBDIR=/usr/lib64 install-includes install-static; make clean"
bash -c "cd zstd/lib;make PREFIX=/usr LIBDIR=/usr/lib CFLAGS=-m32 install-static; make clean"
