#!/bin/sh
bash -c 'cd zstd/lib;make PREFIX=/usr LIBDIR=/usr/lib64 CFLAGS=-fPIC install-includes install-static; make clean'
bash -c 'cd zstd/lib;make PREFIX=/usr LIBDIR=/usr/lib CFLAGS="-fPIC -m32" install-static; make clean'
