#!/bin/sh
if [ "$ARCH" == "x86" ]; then
  bash -c 'cd zstd/lib;make PREFIX=/usr LIBDIR=/usr/lib CFLAGS="-fPIC -m32" install-includes install-static'
else
  bash -c 'cd zstd/lib;make PREFIX=/usr LIBDIR=/usr/lib64 CFLAGS=-fPIC install-includes install-static'
fi
