name: Darwin

on:
  schedule:
    - cron:  '0 1 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.target == 'arm64' && 'macos-14' || 'macOS-13' }}
    strategy:
      fail-fast: false
      matrix:
        target: [arm64, x86-64]
        include:
          # default lisp used is sbcl-bin/2.3.8
          - lisp: 'sbcl-bin/2.3.8'
    environment: SET_VERSION

    steps:
      - uses: actions/checkout@v4

      - name: setenv
        run: |
          echo "$HOME/.roswell/bin" >> $GITHUB_PATH
          echo "ROSWELL_BRANCH=master" >> $GITHUB_ENV
          echo "ROSWELL_INSTALL_DIR=$HOME/.roswell" >> $GITHUB_ENV

      - name: Install Roswell
        env:
          LISP: ${{ matrix.lisp }}
          CFLAGS: -mmacosx-version-min=10.9
          CXXFLAGS: -mmacosx-version-min=10.9
          LDFLAGS: -mmacosx-version-min=10.9
        run: |
          brew install automake autoconf
          curl -L https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh | sh
          ros install snmsts/sn.github roswell/sbcl_bin
          make zstd
          bash -c "cd zstd/lib; sudo make PREFIX=/usr/local install-includes install-static clean"
          rm -f /usr/local/lib/libzstd*.dylib /opt/homebrew/lib/libzstd*.dylib
      - name: build & upload
        env:
          VERSION: ${{ secrets.VERSION }}
          GITHUB_OAUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ARCH: ${{ matrix.target }}
          CFLAGS: -mmacosx-version-min=10.9
          CXXFLAGS: -mmacosx-version-min=10.9
          LDFLAGS: -mmacosx-version-min=10.9
        run: |
          if [ "$VERSION" = "" ]; then
            make latest-version compile archive upload-archive;
          else
            make compile archive upload-archive;
          fi
