name: osx

on:
  schedule:
    - cron:  '0 1 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-10.15
    strategy:
      matrix:
        lisp: [sbcl-bin/2.0.0]
        target: [x86-64]
    environment: SET_VERSION

    steps:
      - uses: actions/checkout@v2

      - name: setenv
        run: |
          echo "$HOME/.roswell/bin" >> $GITHUB_PATH
          echo "ROSWELL_BRANCH=master" >> $GITHUB_ENV
          echo "ROSWELL_INSTALL_DIR=$HOME/.roswell" >> $GITHUB_ENV

      - name: Install Roswell
        env:
          LISP: ${{ matrix.lisp }}
        run: |
          brew install automake autoconf
          curl -L https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh | sh
          ros install snmsts/sn.github
          rm /usr/local/lib/libzstd*.dylib

      - name: build & upload
        env:
          VERSION: ${{ secrets.VERSION }}
          GITHUB_OAUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ARCH: ${{ matrix.target }}
        run: |
          if [ "$VERSION" = "" ]; then
            make latest-version compile archive upload-archive;
          else
            make compile archive upload-archive;
          fi
