name: qemu

on:
  #schedule:
  #  - cron:  '0 1 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ secrets.VERSION }}
      ARCH: ${{ matrix.target }}
      SUFFIX: ${{ matrix.suffix }}
      LINKFLAGS: ${{ matrix.linkflags }}
      ROSWELL_BRANCH: master
      GITHUB_OAUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - target: ppc64le
            suffix: '-glibc2.40'
            lisp: sbcl-bin/2.4.0
            image: 'ppc64le/debian:trixie'
            os: linux
            docker-platform: linux/ppc64le
          - target: ppc64le
            suffix: '-glibc2.39'
            lisp: sbcl-bin/2.4.0
            image: 'ppc64le/ubuntu:24.04'
            os: linux
            docker-platform: linux/ppc64le
  
    environment: SET_VERSION

    steps:
      - uses: actions/checkout@v4
      - name: setenv
        run: |
          echo "$HOME/.roswell/bin" >> $GITHUB_PATH
          echo "ROSWELL_BRANCH=release" >> $GITHUB_ENV
      - name: checkenv
        run: |
          uname -s
          uname -m
          echo $ROSWELL_INSTALL_DIR
          echo $ROSWELL_BRANCH
      - name: Install Roswell
        env:
          LISP: ${{ matrix.lisp }}
        run: |
          curl -L https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh | sh
          ros install snmsts/sn.github
          make latest-version zstd sbcl
          echo 2.3.11 > version
          touch branch
      - name: compile on qemu
        uses: uraimo/run-on-arch-action@v2
        with:
          arch: none
          distro: none
          base_image: ${{ matrix.image }}
          dockerRunArgs: |
            --volume "${PWD}/artifacts:/artifacts"
          env: |
            ARCH: ${{ matrix.target }}
            SUFFIX: ${{ matrix.suffix }}
          install: |
            apt-get -qq update | true
            apt-get -qq install sbcl | true
            apt-get -qq install git build-essential curl
            #cd /tmp;mkdir -p /tmp/clisp;curl -L -O https://github.com/roswell/clisp_head/releases/download/24.9.7/clisp-24.9.7-${{ matrix.target }}-linux-static-binary.tar.bz2; tar xf clisp-24.9.7*
          run: |
            #LISP_IMPL="/tmp/clisp-24.9.7-${{ matrix.target }}-linux-static/bin/clisp" \
            LISP_IMPL='sbcl --dynamic-space-size 700MB --lose-on-corruption --disable-ldb --disable-debugger' \
            SBCL_OPTIONS='' \
            make latest-version compile archive
            mv *.bz2 /artifacts
      - name: upload-image
        env:
          GITHUB_OAUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ secrets.VERSION }}
          ARCH: ${{ matrix.target }}
          IMAGE: ${{ matrix.image }}
          SUFFIX: ${{ matrix.suffix }}
          LINKFLAGS: ${{ matrix.linkflags }}
        run: |
          mv ${PWD}/artifacts/* .
          ls
          env FILE=`ls *.bz2` make latest-version upload-archive
