name: WindowsArm64

on:
  schedule:
    - cron:  '0 1 * * *'
  workflow_dispatch:

jobs:
  build-win-arm64:
    runs-on: windows-11-arm
    timeout-minutes: 90
    strategy:
      fail-fast: false
      matrix:
        include:
        - arch: clang-aarch64
          sys: clangarm64
          target: arm64
    env:
      LISP: sbcl-bin
      SBCL_OPTIONS: --fancy
      ARCH: ${{ matrix.target }}
      VERSION: ${{ secrets.VERSION }}
      GITHUB_OAUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    environment: SET_VERSION

    steps:
    - run: git config --global core.autocrlf false
    - uses: actions/checkout@v4
    - uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.sys }}
        path-type: inherit
        release: true
        update: true
        install: 'mingw-w64-${{ matrix.arch }}-clang mingw-w64-${{ matrix.arch }}-toolchain make diffutils curl unzip'
    - name: Run MSYS2 once
      shell: msys2 {0}
      run: |
        pwd
        echo $MSYSTEM
        echo $MSYS2_PATH_TYPE
        echo $PATH
    - name: install roswell
      shell: msys2 {0}
      run: |
        cc -v
        curl -L https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh | sh
        ros install snmsts/sn.github roswell/sbcl_bin
    - name: build sbcl
      shell: msys2 {0}
      run: |
        make zstd
        bash -c 'cd zstd/lib;make CFLAGS="-fPIC" libzstd.a-release;cp libzstd.a /clangarm64/lib;cp *.h /clangarm64/include'
        if [ "$VERSION" = "" ]; then
          OS=windows make latest-version compile;
        else
          OS=windows make compile;
        fi
    - name: install WiX Toolset
      shell: pwsh
      run: |
        choco install wixtoolset
        $wixPath = (Get-ChildItem "C:\Program Files (x86)\WiX Toolset*" | Select-Object -First 1).FullName
        echo "WIX=$wixPath" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
    - name: archive and upload
      shell: msys2 {0}
      run: |
        ls
        if [ "$VERSION" = "" ]; then
          OS=windows make latest-version archive upload-archive;
        else
          OS=windows make archive upload-archive;
        fi
